name: flutter_open_whatsapp
description: A new Flutter plugin that will send Whatsapp message to single user without saving user's number.
version: 0.2.0
homepage: https://github.com/rohit1814/flutter_open_whatsapp

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: infozenplus.com.flutter_open_whatsapp
    pluginClass: FlutterOpenWhatsappPlugin
